# Generated by Django 3.2.8 on 2021-10-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20211015_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('paper_account', 'Paper Account'), ('live_account', 'Live Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('kampala', 'Kampala'), ('Mbarara', 'Mbarara'), ('Gulu', 'Gulu'), ('dar_es_salaam', '\tDar es Salaam'), ('mwanza', 'Mwanza'), ('arusha', 'Arusha'), ('nairobi', 'Nairobi'), ('kisumu', 'Kisumu'), ('mombasa', 'Mombasa'), ('kigali', 'Kigali'), ('butare', 'Butare'), ('gitarama', 'Gitarama'), ('bujumbura', 'Bujumbura'), ('gitega', 'Gitega'), ('muyinga', 'Muyinga')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_of_residence',
            field=models.CharField(choices=[('uganda', 'Uganda'), ('kenya', 'Kenya'), ('tanzania', 'Tanzania'), ('rwanda', 'Rwanda'), ('burundi', 'Burundi'), ('south_sudan', 'South Sudan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
