# Generated by Django 3.2.8 on 2021-10-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211022_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('paper_account', 'Paper Account'), ('live_account', 'Live Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('kampala', 'Kampala'), ('Mbarara', 'Mbarara'), ('Gulu', 'Gulu'), ('dar_es_salaam', '\tDar es Salaam'), ('mwanza', 'Mwanza'), ('arusha', 'Arusha'), ('nairobi', 'Nairobi'), ('kisumu', 'Kisumu'), ('mombasa', 'Mombasa'), ('kigali', 'Kigali'), ('butare', 'Butare'), ('gitarama', 'Gitarama'), ('bujumbura', 'Bujumbura'), ('gitega', 'Gitega'), ('muyinga', 'Muyinga')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_of_residence',
            field=models.CharField(blank=True, choices=[('uganda', 'Uganda'), ('kenya', 'Kenya'), ('tanzania', 'Tanzania'), ('rwanda', 'Rwanda'), ('burundi', 'Burundi'), ('south_sudan', 'South Sudan')], max_length=100),
        ),
    ]
